baseURL = 'https://chapanexum.github.io/'
languageCode = 'pt-br'

title = 'Projeto monitorias'
theme = 'hugo-theme-learn'
[params]
  themeVariant = "mine"
  disableLandingPage = true

enableRobotsTXT = false
